
/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    kotlin("jvm")
}

repositories {
    mavenCentral()
    jcenter()
}

dependencies {
    implementation(kotlin("stdlib"))

//    // Align versions of all Kotlin components
//    implementation(platform("org.jetbrains.kotlin:kotlin-bom"))
//
//    // Use JUnit Jupiter API for testing.
//    testImplementation("org.junit.jupiter:junit-jupiter-api:5.6.2")
//
//    // Use JUnit Jupiter Engine for testing.
//    testRuntimeOnly("org.junit.jupiter:junit-jupiter-engine")
}

//tasks.test {
//    // Use junit platform for unit tests.
//    useJUnitPlatform()
//}

